### ISSUE TITLE
Parameters from yaml interpreted as lists instead of correct interpretation of int

### ISSUE THREAD

**Issue by kimyenn** [nteract/papermill#214]
I have a yaml file which contains the following:

```
x:
  - 10.0
  - 20.0
y:
  - 12.0
  - 16.0
```

I am expecting the notebook to run using different combinations of x & y. However, errors are encountered instead since x and y are interpreted as two lists of [10.0, 20.0] and [12.0, 16.0]. Is this a bug or should I be able to pass multiple values for a parameter? I receive this error when the notebook attempts to use x or y. 

`TypeError: unorderable types: list() < int()`

Thanks

**Comment by MSeal** [comment]
@kimyenn The parameters are treated as independent objects rather than a grid search of notebook executions. So the behavior of receiving two lists is as expected.

If you wanted to iterate through a value and run a notebook for each combination you'd have to do that outside of the papermill call -- or make a parent notebook that calls papermill internally to a second notebook for each combination.

**Comment by MSeal** [comment]
Going to close this issue. Feel free to reopen if this didn't answer your question :)

**Comment by kimyenn** [comment]
@MSeal Thanks for the clarification. The solutions you presented worked well!
