### ISSUE TITLE
Handling secrets

### ISSUE THREAD

**Issue by mindsbackyard** [nteract/papermill#271]
Currently all passed parameters are stored in the output notebook for later inspection. Sometimes though, one would like to pass information which should not be disclosed in the output notebook, e.g., authentication tokens, cryptographic keys, passwords, etc. Even when run in report-mode papermill, injected parameters are only hidden.

As a workaround secrets can be passed by usin environment variables. Though, if the notebook is executed on a remote engine, e.g., as in #229; exposing an environment variable might not be possible.

A possible solution could be to introduce new `secrets` cells in the notebook, similar to the existing `parameters` cells. Secrets would be injected using `--secrets`, `--secrets-raw`, etc., options on the command line. Injected secret cells would be sent to the executing engine, but wouldn't be saved in the output notebook. Alternatively, injected secrets could be stored in an encrypted format for later inspection. The encryption key could either be explicitly specified or generated on the fly and returned in the invoking client.

**Comment by MSeal** [comment]
The way we've been handling secrets is to pass encrypted strings as the parameter with tools like open encrypt and then inside the notebook decrypt the results. There's a few reasons to take this approach:

1. The notebook is reproducible in different environments provided the user has permission or access to decrypt the secrets. Remote execution and local execution operate in the same way
2. Passing the raw secrets to the notebooks both saves the secret in the json of the document and persists the secret in the caller's history / execution logs. So we avoid leaving the secrets in plain text anywhere that's persisted
3. The encryption / decryption tools aren't mandated by papermill. We want to keep papermill as simple as we can without impeding real work. This may be one of the cases where the implementations would dictate a few opinions on secrets that might not apply to everyone or complicate the library.

If we were to look into adding secrets to the command line interface it'd have to be a secrets file which we encrypt before passing to the notebook document. Otherwise we'd leak information in ways that might defeat the secret's purpose.

**Comment by betatim** [comment]
Are there open-source tools/libraries you can recommend for people to use to implement the "decrypt if user has permission" workflow?

My guess would be there are a few people out there who want to do something like this so if we can provide some pointers for them to follow everyone would be happier (and more secure?).

**Comment by MSeal** [comment]
Python has a Crypto package with raw AES support: https://stackoverflow.com/questions/16761458/how-to-decrypt-openssl-aes-encrypted-files-in-python which is compatible with openssl / AES encoding tools. This solution does require that you manage the keys yourself.

Another solution is to use https://pynacl.readthedocs.io/en/stable/secret/ which has more wrapped support for crypto primitives.

Many times when dealing with secrets there's already an identification / authorization system inplace that you're pairing with, so the tool to use should relate to the identity you're using on the machine executing (i.e. your ssh key, oath identity, etc). Given that, usually those tools have secret management and decryption built in that you can call from a `%%bash` cell.

**Comment by mirekphd** [comment]
We have also run into this problem. For our data scientists it looks like a blocker. We can use a safe input method in the controller notebook that would allow manual password entry (getpass.getpass()), we can encode the password with base-64, but the output notebook preserves this password in the 'injected-parameters' input cell in a very apparent format `pass_var_name="pass123"`. I've created a stackoverflow issue to ask how to delete this 'injected-parameters` cell, see: https://stackoverflow.com/questions/62022603/how-to-delete-a-jupyter-notebook-input-cell-programmatically-using-its-tag

**Comment by MSeal** [comment]
Never pass secrets in plaint or compressed text to any application if you can avoid it. You need to pass an encrypted base64 string and use a key in memory to decrypt the value. Then leave that value only in memory. Never print, echo, or translate into code the actual secret and if you do you should consider that secret compromised if it leaves your closed system in anyway.

Deleting the parameter cell isn't sufficient here to avoid leaking the secret as it can escape to various insecure places along the way and your guarantee for eliminating access to the information is weak unless it's never printed.

**Comment by mirekphd** [comment]
We had an in-memory solution based on env vars, but it was considered too
weak (as admin I could remote shell to the pod an get the env contents), so
data scientists used keyrings instead, which no longer work with
papermill... Unless you run them in the master controller notebook. Note
this is an on-prem air-gapped server farm controlled by security-enhanced
Openshift, very different scenario from the public cloud... The secrets are
encoded, kept only in memory, deleted from globals() after use. I even
managed to delete your injected-parameters cell now.

Incidentally, why not inject parameters to globals() in an invisible way?
It's not me who does the printing here:)

**Comment by MSeal** [comment]
> It's not me who does the printing here:)

By passing the secrets to papermill it may log them to a file in the kernel, the command itself my by logged by system history, and the contract for how parameters is handled is fairly clear that they'll be pasted in plain text. If anything on your machine gets logged or shipped outside the box you have now leaked the secret and you may not even know it's been leaked.

> Incidentally, why not inject parameters to globals() in an invisible way?

Because then the output is not reproducible with the output document without additional information. If you pass encrypted secrets and have a system for decryption you care calling it's visible what's needed to successfully rerun the notebook.

> We had an in-memory solution based on env vars, but it was considered too weak (as admin I could remote shell to the pod an get the env contents),

True but if you're an admin you could steal the secrets already because you have root, or supervisor-like, permissions over the machine and the credentials the execution context can access. What security you need depends on the thread-vector you're solving against. Usually protecting from one's own admins is left off the list of things to protect against unless it's a highly secure situation (e.g. gov clouds sometimes).

> I even managed to delete your injected-parameters cell now.

Be careful that you didn't save with it first then overwrite it without the value. That can also leak the secret, especially when sending to a blob store target (e.g. S3 can have the older version still around). If you never save the cell with the secret at all, you're probably safe on the output half of the equation.

Hopefully these comments are helpful. I'm trying to emphasize some security opinions here from a number of engagements with secure execution contexts I've had to work with in the past. Maybe try looking at solutions like vault for have secured tokens or credentials you need at runtime. Those tool chains have thought through the models quite well on what you should be or shouldn't be doing with sensitive information.

**Comment by mirekphd** [comment]
Very helpful indeed, thank you. I need to point out two issues though:)

> > Incidentally, why not inject parameters to globals() in an invisible way?
> 
> Because then the output is not reproducible with the output document without additional information. 
I realized that was the purpose, after all reproducibility is the whole point. But if someone knows already which parameters got injected by papermill? We for instance pass the names and values of these parameters in a separate dict and together with all other variables we preserve them in a collective json saved in object storage (mino, part of mlflow). So how about adding this ability to pass directly to the globals() as an option (say 'stealth mode=True')? The simplest solution would be to the injected-parameters cell immediately after execute_notebook() it executes (which can be done - I'm already doing it after the function finishes or crashes).

> If you pass encrypted secrets and have a system for decryption you care calling it's visible what's needed to successfully rerun the notebook.
But that's a bit of a catch-22, as it needs to be fully automatic (with no manual intervention from the user) which means that the adversary (e.g. me as project admin or cluster admin) could also execute the same automation procedure to retrieve the data. E.g. if there a private key is needed, the attacker may also gain access to the key, which is very likely because the notebook has to gain access to it without extra user invervention, using some predictable information... I don't believe that extra encryption can add additional security if the key retrieval has to be automated (I wouldn't know how to do it without user input (such as second-layer password to the keyring), so I did not bother to implement anything more fancy that base-64, as it can be broken just as easily IMO).
