### ISSUE TITLE
generated images as output do not render in a generated notebook

### ISSUE THREAD

**Issue by stillmatic** [nteract/papermill#278]
Hi, I'm trying to run some notebooks using `pm.execute_notebook(s3_path, s3_path2, params)` and am able to generate a notebook, which I can view via nbviewer, and everything is correct except for there are no images rendered.

I am making several matplotlib calls, e.g. 

```
import matplotlib.pyplot as plt
fig, ax1 = plt.subplots()
[...do some stuff...]
plt.show()
```

for what it's worth i am doing these in a loop, in the same cell. 

is this intended behavior? do i need to do some device switching or something, to make "headless execution" work correctly?

**Comment by betatim** [comment]
To store the created images in the notebook (when using matplotlib) you need to have `%matplotlib inline` as a "magic" in your notebook. Otherwise I think matplotlib will open a GUI window to show you the plot.

I think calling `plt.show()` multiple times in a cell will result in multiple figures being shown if you use the inline backend (via that "magic" command).

**Comment by stillmatic** [comment]
thanks, adding that magic command did the trick!
