### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by RoyalTS** [nteract/papermill#332]
Would it be possible to provide an up-to-date papermill conda package? Unfortunately [the one that's currently on conda-forge](https://anaconda.org/conda-forge/papermill) is severely outdated.

**Comment by MSeal** [comment]
I'm not sure who setup or was maintaining conda-forges build clones but I'll put in an inquiry into it.

**Comment by betatim** [comment]
The conda-forge package comes from https://github.com/conda-forge/papermill-feedstock/pulls which has some PRs already from the autotick bot (but not super recent ones?). So in principle we should be able to get that more or less for free after making a release to PyPI.

Because it is so heavily automated this can be a good thing for someone with a low amount of time available for contributions to keep an eye on. Might be worth highlighting in the contributing docs that this is something something relatively new can get involved with and help out the project (and learn lots of about packaging).

**Comment by RoyalTS** [comment]
Losing track of the sub-issues. This is just being held up elsewhere?

**Comment by MSeal** [comment]
Yes it's stuck on some conda-forge specific build problems we needed internal folks to help us with. I've been busy with a few items so hadn't checked in on progress the past few days.

**Comment by MSeal** [comment]
Ok we got the last of the issues resolved. Conda-forge now has 0.19.1 available and should keep in sync with PyPI versions moving forward!

**Comment by betatim** [comment]
Thanks for sorting all that out!
