### ISSUE TITLE
Recommendation on unit testing papermill run jupyter notebooks

### ISSUE THREAD

**Issue by mbrio** [nteract/papermill#334]
Do you have any guidelines for unit testing papermill run jupyter notebooks?

**Comment by MSeal** [comment]
So this would depend on what you want to test exactly.

Since papermill is creating subprocesses and potentially running arbitrary code, many times you want integration tests for you notebooks. These would be post-build CI run which ran your notebooks against test (or production) utilities to ensure that you can communicate across systems.

If your notebooks are more self-contained you have a few other options. In papermill itself we make our test suite depend on ipython and simply call papermill's execute_notebook and then use nbformat or papermill's iorw modules to read the results and confirm specific actions occurred.

A final approach if your notebooks are complicated and would call into many external systems but you still want to test that you're parameterizing your notebook correctly you could register a [custom engine](https://github.com/nteract/papermill/blob/master/papermill/engines.py#L357) in your setUp which mocks all the cell execute calls and then returns the mock object. You could then assert that specific code cells were activated without actually running anything.

Hope this helps.
