### ISSUE TITLE
How do you handle notebook errors when executing it with Papermill ?

### ISSUE THREAD

**Issue by fx86** [nteract/papermill#344]
How do you handle errors in notebooks that Papermill executes ? 

For example, I added an `assert False` statement in a notebook and executed it with Papermill. I was hoping to see an error flag with a graceful shutdown as an output from the `Papermill.execute` call but instead I got an error trace. 

![image](https://user-images.githubusercontent.com/1297203/56189072-b4ddfb00-6044-11e9-83ae-a202f45e412b.png)

It would be great to get access to the exception object (or the exception content at least) raised, with which I could alter the post-error behaviour of the papermill job. Is there a way to do this  currently ?

**Comment by MSeal** [comment]
There is not currently a way to propagate the exact exception back from the kernel process. Because the underlying execute could be in any language (including `!some bash command`) it's hard to guarantee any exception passing. Even python versions between the kernel and papermill's process might be different.

However, what you do have is all the components that make up the exception:
https://github.com/nteract/papermill/blob/master/papermill/exceptions.py#L24-L28
which you could use to re-wrap in your own exception types or filter to respond to particular failure modes.

**Comment by fx86** [comment]
Thanks, @MSeal.
