### ISSUE TITLE
Option for execute_notebook() to disable expansion of parameters in the input path

### ISSUE THREAD

**Issue by 0anton** [nteract/papermill#392]
Dear papermilll maintainers,

Is it possible to have an option for execute_notebook(), which disables expansion of parameters in the source path?

I am using parameters in the file name to automatically produce multiple reports stemming from the same source notebook, e.g.:

```
papermill.execute_notebook('{param}/notebook.ipynb', 'value1/notebook.ipynb',
                                parameters={'param': 'value1'})
papermill.execute_notebook('{param}/notebook.ipynb', 'value2/notebook.ipynb',
                                parameters={'param': 'value2'})
```
                                
I cannot use this pattern with the current version of papermill, because it expands the input notebook name producing:

```
value1/notebook.ipynb -> value1/notebook.ipynb 
value2/notebook.ipynb -> value2/notebook.ipynb 
```

This fails because the source notebook does not exists.

I'd like to have all target reports produced from the single template notebook, which includes parameters in the path:
```
{param}/notebook.ipynb -> value1/notebook.ipynb 
{param}/notebook.ipynb -> value2/notebook.ipynb 
```

I cannot do it, because papermill expands parameters in both source and target file.

My suggestion is to introduce a bool option _parametrize_input_path_ in _execute_notebook()_, which disables expansion of parameters in the source path, like:

```
papermill.execute_notebook('{param}/notebook.ipynb', 'value1/notebook.ipynb',
                                parameters={'param': 'value1'}, 
                                parametrize_input_path=False)
```

I include suggested PR to the issue.

Kind regards,
Anton

**Comment by MSeal** [comment]
Sorry for the delayed response.

I'm a little confused why your source notebook would have a `{param}` literal in the path, specifically the `{` symbols. It seems like your input path could easily be calculated before you pass it into papermill if you needed to apply some parameter ahead of time (with a `.format` call). If you really need `{param}` exactly in your input path you can escape the `{` and `}` characters by doing `{{param}}` instead.

I'm somewhat against adding this option, not because it wouldn't work, but because it complicates the papermill interface (including the cli). I would  Is there something I am missing about the input path here?

**Comment by 0anton** [comment]
Hi Matthew,

Thank you for taking that issue! I am using papermill to run a (template-)notebook with several different parameters and keep calculation results in different target NBs. To avoid name collision for target notebook I use include placeholders in the path (directory of filename paths), which I expand with _.format_ for the target notebooks using parameter values (with slight specially processing to produce valid paths) . Using curly brackets and _.format_ is convenient and looks very python way for me to do so.

I was surprised when I saw that papermill expands NB parameters in source and target filenames. I still don't understand the reason and cannot find any documentation about that. I think I understand that expansion of the target notebook follows the same logic as I do - automatically place parametrized output versions into different files. I believe it is still very risky to uses parameter values directly to produce target file names, because it will certainly produce in some cases prohibited names. I do some prettyfing for path filenames. So considering said above, I believe that also even parameter expansion in the path for output NB in the current form is also not useful.

But parameter expansion in the source notebook is completely not understandable for me. The purpose it to run _one_ NB with different parameters, but with source NB expansion we try to process different NBs, using parameter values.

So, if there is really no usage for the parameter expansion in source notebook, then it is also not worth adding additional parameter in the API, as I suggested in PR. I would then completely remove the code, which expands parameters in source path.

Additionally. due to high risk of producing non-valid target paths, I would also refrain from expanding target paths in the library and let this to be done by caller of the library. Or, if some client already rely on this feature, I'd make it possible to disable.

My only possible workaround currently (please correct me if I am wrong) is to copy the source notebook several times under expanded file path for each parameter combination and call papermill asking using the same notebook for input and output, like:

```
output_nb = "{param}/notebook.ipynb".format(parameters)
copyfile("{param}/notebook.ipynb", output_nb)
papermill.execute_notebook(output_nb, output_nb,
                                parameters={'param': 'value1'})
```


But I am not sure if papermill can handle the situation of the same and target NB.

What do you think about that?

Kind regards,
Anton

**Comment by 0anton** [comment]
Added PR #397 to extend CLI accordingly.

**Comment by MSeal** [comment]
Hi Anton,

I disagree with

> So considering said above, I believe that also even parameter expansion in the path for output NB in the current form is also not useful.

It's got some nice utility for simple cases to avoid repeating yourself. I'd instead argue that having `{` and `}` in a filename is much more problematic as a general pattern because your raw filename has command line operators in it.

> So, if there is really no usage for the parameter expansion in source notebook

I have a real use-case where there's a number of experiment template notebooks, and the user passes the experiment id into the papermill call. It simplifies their execution if they can pass once and not pre-expand it.

That being said I do believe there's a simple work-around that I mentioned in the earlier response, that doesn't require any file copying:

Make the input_path escape the formatting: `input_nb = "{{param}}/notebook.ipynb"`

```
papermill.execute_notebook('{{param}}/notebook.ipynb', '{param}/notebook.ipynb', parameters={'param': 'value1'})
```

will read the input file `{param}/notebook.ipynb` and output to `value1/notebook.ipynb`

> But I am not sure if papermill can handle the situation of the same and target NB.

It can and does work. The `injected-parameters` tagged cell gets replaced instead of inserted if you run it multiple times. You can just lose history of execution outcomes because you're overwriting the file each run.

I'd more amendable to disabling all pathing formating rather than just input or output as an option if we did go forward with merging anything. But given there's an easy way to escape the formatting I'd rather just promote that pattern than clutter the API options with another configurable piece. It may sound trivial but one of the niceties of papermill is the opinionated execution without overwhelming options. Generally for much more customized execution patterns we point to [nbconvert](https://nbconvert.readthedocs.io/en/latest/), which papermill uses under the hood today.

I normally don't like pushing back on PR-additions but I'm still in the camp of the format escaping is the better pattern here. What would be a really nice addition would be doc updates for path parameterization, including how to escape out of it with the `{{}}` pattern. The feature is relatively new and we always lag a little on good doc updates.

Thoughts?

**Comment by 0anton** [comment]
Hi Matthew,

Thank you for the extended explanation.

I understood that people use expansion of parameters in path like in the following pattern:
```
for i in range(10):
    papermill.execute_notebook('{experiment_id}/notebook.ipynb', 'out/{experiment_id}/notebook.ipynb', parameters={'param': i})
```
This was new to me. Sure, if it is a useful feature, it shall be kept.

I helped myself by preprocessing the input path as you suggested with the following escaping function.

```
def _escape_curly_brackets(str:str) -> str:
    """Escape curly brackets e.g. {param1}/param2} will be {{param1}}/{{param2}}"""
    return re.sub(r'{(\w+)}', r'{{\1}}', str)

```

Thank you for giving this hint. I was not aware of this method.
I think we can close this for now.

Anton
