### ISSUE TITLE
Cleanup phase before exiting when papermill is interrupted?

### ISSUE THREAD

**Issue by juhoautio** [nteract/papermill#431]
**Is there any common way to handle cases where one would need papermill to execute some cleanup cell(s) before papermill exits?**

This should happen regardless of why it's being terminated – due to an error, or because the papermill process was killed.

So it would be similar to the `finally` block of a `try-finally` clause in Python or Java.

----

My sparkmagic use case:

I have notebooks that use sparkmagic to launch livy sessions. Each livy session ends up as a running YARN application, reserving some resources from a cluster. The last cell of my notebook tells sparkmagic to terminate the session(s).

If I run such notebook successfully with papermill it works as expected: the livy session is terminated before papermill exits. But if I interrupt papermill while it's running, the livy session / YARN application is left running (until it finishes and/or livy session times out).

**Comment by MSeal** [comment]
This is a hard problem to solve generally, especially since the kernel is in a completely different process (and possibly different execution language). The process failing falls into two categories, graceful and non-graceful. In the graceful case (e.g.: user Ctr-C) one could allow the kernel python process to perform cleanup via https://docs.python.org/3/library/atexit.html. This is what I would do for expected exits. For ungraceful exits (like OOM) you're not going to be able to take any action in the kernel process, so I'd suggest you set a reasonable timeout of the spark session config so it will release the resources without waiting too long on the spark side.

**Comment by juhoautio** [comment]
Great answer, thanks.

In my case atexit works quite well for cleaning up the resources, because it's not common that the notebook itself would crash abrubtly.

The code that I used for now:

```python
def cleanup_spark_session():
    try:
        get_ipython().run_line_magic('spark', 'cleanup')
    except:
        pass

def register_cleanup_on_notebook_exit():
    import atexit
    atexit.register(cleanup_spark_session)

def create_spark_session(host):
    register_cleanup_on_notebook_exit()
    get_ipython().run_line_magic('spark', 'add -l python -u http://{}:8998'.format(host))
```

----

Otherwise, while testing this I stumbled on the sparkmagic that was previously reported here as issue https://github.com/nteract/papermill/issues/330.

I also realized that it's not papermill-specific problem, and as expected found it reported on sparkmagic's side: https://github.com/jupyter-incubator/sparkmagic/issues/518.

Interestingly the proposed fix for the problem also includes some sparkmagic cleanup: https://github.com/jupyter-incubator/sparkmagic/pull/519 - but it seems surprising to me that it would be done only in failure cases. Why not always on exit, like my code above?
