### ISSUE TITLE
Papermill doesn't pin dependencies

### ISSUE THREAD

**Issue by abhin-rk** [nteract/papermill#465]
Yesterday `nbformat` released a new version. Turns out they didn't include all the files in their released package and had to [release again with the fix](https://github.com/jupyter/nbformat/pull/158). It also turns out that the company I work for had a deployment between the original release and the bugfix release of `nbformat`. As a result, our pipeline broke.

I think one of the underlying issues in this system is that papermill doesn't pin its dependencies. So when an underlying package releases a new version, a previously tested version of papermill becomes entirely untested and susceptible to failure.

Is version pinning something that the maintainers of papermill interested in? If so, I'd be happy to contribute some time towards making a PR.

**Comment by MSeal** [comment]
That was my bad on the nbformat release, apologies for that. So generally it's not a good idea to pin a library's dependencies because if you did it would make it nearly impossible for applications to include the library and not have dependency conflicts. Here's a short article I found that outlines some of those tradeoffs and patterns: [to-pin-or-not-to-pin-dependencies](http://blog.chrisgorgolewski.org/2017/12/to-pin-or-not-to-pin-dependencies.html)

So I wouldn't recommend making changes in papermill itself. Where there should be pins and/or unittests should be in your application's CI toolchain so that you only release code that's passed all of your unit and integration tests. This also protects you from incompatible versions in your application that might work independently but not together with the current pinned application (or latest) versions.

**Comment by abhin-rk** [comment]
That's a fair point. Thank you for the article; it was helpful. I'm happy to close this issue.
