### ISSUE TITLE
cache run results

### ISSUE THREAD

**Issue by AaamberW** [nteract/papermill#524]
Would be nice if papermill supports caching, as in when a run is interrupted by exceptions, after fixing the cell the next run will pick up from the broken point, so that it'll save time from repeating running previous cells.

**Comment by MSeal** [comment]
Hi @AaamberW , thanks for posting the issue.

So papermill doesn't cache any run context because it would need to keep a kernel process alive and no process would be monitoring that one to clean it up once papermill returns an exit code. Dumping the kernel memory state isn't feasible either because there's not a guaranteed way to restore a process memory state (pickling all globals for python isn't a reliable solution to this) to pickup from.

If you had a secondary process manager that was responsible for cleanup of kernels you could in theory [register a modified engine](https://papermill.readthedocs.io/en/latest/extending-entry-points.html#developing-a-new-engine) and not wrap execution in a [cleanup context](https://github.com/nteract/papermill/blob/65078277e9e1b2b1a2d39250fbfa18ebd8b59cfd/papermill/clientwrap.py#L43).

That's pretty complicated and process management is prone to issues. You might be better served by making the code you're executing cache expensive requests or processing to speed-up catching back up to a failure. Or perhaps by developing in a notebook environment until you're confident the code is unlikely to fail part way through execution.

**Comment by willingc** [comment]
Closing this issue since it appears beyond the complexity that we wish to implement with papermill. Thanks.
