### ISSUE TITLE
jupyter_client dependency version overridden in requirements.txt

### ISSUE THREAD

**Issue by ajbozarth** [nteract/papermill#526]
As previously raised in #486 #492 #500 #522 and #523 if papermill is used in an environment with an older version of `jupyter_client` it will throw an error. This is caused by the dependency `nbclient>=0.2.0` that depends on `jupyter_client>=6.1.0`.

This dependency is overridden by papermill by having `jupyter_client` in `requirements.txt` without a version, meaning any version (even an older one) is accepted if already installed. To make sure the expected version of `jupyter_client` is installed we should set `jupyter_client>=6.1.0` to match `nbclient`.

Though as said in the previous issues this is easy to address for users by having then just upgrade, for downstream projects that rely on papermill it would require them to set a version for `jupyter_client` in their own requirements even though they don't directly use it, which is generally bad practice.

**Comment by MSeal** [comment]
Hmm I did some further testing and this doesn't fully resolve the issue because of how pip handles nested version requirements, even with the new `--use-feature=2020-resolver`. I'm going to remove the jupyter_client dependency entirely from requirements and do a patch release so folks stop hitting this issue.
