### ISSUE TITLE
Running a kernel that doesn't have papermill installed, using an environment that does, for CI

### ISSUE THREAD

**Issue by thvasilo** [nteract/papermill#541]
Hello,

I have a use that's related to https://github.com/nteract/papermill/issues/251 but more strict: 

I have an Jupyter notebook that I want to ensure executes to completion in a specific Conda environment (for CI), say `my_conda_kernel`. Because that environment relies on a bunch of pinned dependencies, I would really like to avoid installing papermill on it, as it requires updating core components like jupyter-core. So unlike #251, I can't run `conda install -n my_conda_kernel papermill`

So what I'd like to do is create a new conda env, say `paper-env`, install papermill on that, and then run `(paper-env) $ papermill my_notebook.ipynb out.ipynb -k my_conda_kernel`

Having tried that however, I keep getting errors that jupyter cannot find the kernel specified. I've described the issue in a relevant thread for [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/185#issuecomment-706464815), but I thought I'd solicit some advice here as well, as this seems like a common CI usecase, where we don't want papermill's dependencies polluting the target env.

**Comment by MSeal** [comment]
To do this you need the other kernel spec paths for the second environment visible at runtime. https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs has instructions for this, but usually you need to set the `JUPYTER_PATH` to include the spec directory in your second conda environment where the kernel installed it's spec file. If after that it's still using the wrong environment within that kernel, double check that the kernel json spec fil uses a path to the environment's python / environment setup in it's command so that it's activating the local conda installed environment before executing the kernel itself.

**Comment by willingc** [comment]
Closing this issue since it appears to be addressed. @thvasilo if there are additional questions, I would be happy to reopen this. Thanks to all!
