### ISSUE TITLE
CONTRIBUTING.md has confusing links and grammar for the code of conduct

### ISSUE THREAD

**Issue by amcinnes87** [nteract/papermill#559]
The file says, "Please read our entire code of conduct here. Also, check out the for the Python code of conduct.". Both "here" and "Python" are linked to the same page. The part of "the for the" also seems grammatically incorrect.

Is the second link supposed to point to the PSF CoC?

**Comment by amcinnes87** [comment]
I will happily create a PR if you can tell me what you would like.

**Comment by captainsafia** [comment]
@MSeal @willingc I think we should just reference the Code of Conduct in the nteract monorepo since we did the CoC consulting on that one and it's more consistent than linking to to CoCs.

If Carol and Matt are cool with the above, we should link to https://github.com/nteract/nteract/blob/c585f42f1caba665b17228bdc3601f1297bf3f48/CODE_OF_CONDUCT.md.

**Comment by willingc** [comment]
@amcinnes87 I think that @captainsafia's suggestion is perfect. I doubt @MSeal would object.

**Comment by willingc** [comment]
Just to clarify the nteract link that Safia mentions should be the only CoC link ☀️

**Comment by MSeal** [comment]
I'm +1 for that suggestion @captainsafia and @willingc
