### ISSUE TITLE
add Code of Conduct

### ISSUE THREAD

**Issue by vlasvlasvlas** [nteract/papermill#576]
Hi!

i think its important to include de code of conduct, i added here in my fork:
https://github.com/vlasvlasvlas/papermill/blob/main/CODE_OF_CONDUCT.md

thanks!

**Comment by MSeal** [comment]
Do you feel the link from https://github.com/nteract/papermill/blob/main/CONTRIBUTING.md to the organization CoC is insufficient? We left it as a link so that updates across the organization's policy didn't have to do individual updates in the number of individual repos. Though I think it's rarely changed in the past couple years.
